travis:
  secure:
    BINSTAR_TOKEN: TbJqMc4CybNNq0aeuK/zGxGMc5qDj76Awnxcbb9XAIQ06xhjQnQJhPcKE6WGDZ5f+022LC94CzJGHsMZdvEQl7Y53wagDCxJZBHO7qBQmhCNylTpiC2QsjMc4YWWmEhSm9PINslw2RZSwKKhwFph6dCezksx3EwhWRpqM8jyF6+SrZwXpkM4s9r9HA6SL0rWmFAUrGExwOKMHsk0q9OpVBiTbzec2ER5jNXret+dmWHmrQsM3OuJfjI6YLV0cic6Q1GmBYlYyrHQQBI5hJU627kHVCfQBa8QaFOvvKO74wuYZFo8N7j3+WgSN+lMhmtNUIKaBwdXwkVg/4597VQQcYmv//9T586Dj6MQOFhxIP+HLOVIEzWSjDsPfei4zOf68J/p6gkxhK2EQH3qXjx9AF9E6GPbvLuXzWmFZxT825lWorgyT8jOrGBGN06+v39mxN/DYKa0au2R7PNRcvZUkNzvZnqiXgyf3K6nyz2vHEyuAMH8M3QUd2Y4H3R4vXeBbms4Vd/UA1hRnio0NVW0FbB92lAkwq8E/yXiLRb6nr17eiWitggZmRAH1UZ2blO7iHx2SI/PPiZtQ3jtovpNvVh9VIwmOj16XPqXNRv08sF8yZ4BMJw/3oCDOVQS+PP+Sy+29X3l1zyP6vTMJaA4xLxn2lucuhf7QJsMghr/6L4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
